### ISSUE TITLE
Issue for installing

### ISSUE THREAD

**Issue by AmirMardan** [aaspip/pyseistr#2]
Hi,

I get the following error while installing the package using `setup.py` on GitHub or PyPI. While I have `numpy` installed in the used environment, the error is for not having `numpy` installed. 

OS: Mac M1

```bash
Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/Users/amir/repos/venvs/seismic_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/amir/repos/venvs/seismic_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/amir/repos/venvs/seismic_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jc/hrg0sr5n11j94h4ltbj9dscw0000gn/T/pip-build-env-5b_g4cco/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 483, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jc/hrg0sr5n11j94h4ltbj9dscw0000gn/T/pip-build-env-5b_g4cco/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jc/hrg0sr5n11j94h4ltbj9dscw0000gn/T/pip-build-env-5b_g4cco/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/jc/hrg0sr5n11j94h4ltbj9dscw0000gn/T/pip-build-env-5b_g4cco/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/jc/hrg0sr5n11j94h4ltbj9dscw0000gn/T/pip-build-env-5b_g4cco/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by chenyk1990** [comment]
You need to install numpy.

Simply by

pip install numpy

**Comment by AmirMardan** [comment]
As I mentioned, I had `Numpy` installed in the environment I'm using. Having a configuration file ensures there wouldn't be any issues with package requirements.

**Comment by chenyk1990** [comment]
Sounds good!
